### ISSUE TITLE
This project has not been updated for 4 years

### ISSUE THREAD

**Issue by masx200** [koajs/koa-range#22]
This project has not been updated for 4 years, and it may not be updated again in the future. I suggest creating another branch for continued maintenance.

https://github.com/masx200/koa-range

**Comment by jonathanong** [comment]
@masx200 I just added you as a contributor here, so you don't have to fork :) FYI easier to ping me via email or twitter

**Comment by jonathanong** [comment]
@yorkie @dead-horse can you grant me "jongleberry" and masx200 publish rights to `koa-range`?

**Comment by masx200** [comment]
Thanks, I don't know how to write unit tests, and I'm just an amateur programmer.




---Original---
From: ***@***.***&gt;
Date: Wed, Aug 18, 2021 04:09 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [koajs/koa-range] This project has not been updated for 4 years (#22)




 
@yorkie @dead-horse can you grant me "jongleberry" and masx200 publish rights to koa-range?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mreinstein** [comment]
I'd be willing to help with maintainership. I have a lot of other npm modules that I've also been lightly maintaining. What I'd like to do is get the changes from @koa/range merged back in here, publish a new version, update old deps, etc.

My username on npm and github are the same (mreinstein) Is this something you'd be open to @jonathanong ?

**Comment by mreinstein** [comment]
I've been added to the list of maintainers, and I'm looking at this now.

I've also merged one of your PRs that fixes several issues, but I'm concerned that it might be breaking some use cases because some of the tests fail, so I'm hesitant to publish a new npm module with these changes (yet.)

One thing that strikes me as a bit odd about this middleware is it includes the actual response handling of the body. I would think that would be very dependant on _what_ is being served; I don't think we can reliably send the body in a way that works for every conceivable payload.

I might explore refactoring this middleware to remove the actual payload sending. Something like this maybe?:
```javascript
import range from 'koa-range'


app.use(range())

app.use(async (ctx, next) => {
    if (ctx.url === '/big_video.webm') { 
        if (ctx.request.range)
            ctx.response.body = fs.createReadStream('./big_video.webm', { start: ctx.req.range.start, end: ctx.req.range.end })
        else
            ctx.response.body = fs.createReadStream('./big_video.webm')
    } 
}
```

My thinking is that it really shouldn't be `koa-send`'s job to try to figure out exactly how to stream back the body; it's very dependent on the content being requested.

For example, one could imagine a streaming radio service being hosted on one endpoint, and that might be proxied over a socket, or some other source that doesnt come from the file system. In it's current form `koa-send` can't handle that because it bakes in the assumption that the content is on the filesystem.

Additionally it also opens up the possibility of supporting non-byte entries; newer versions of the spec for request range allow for non-byte based range units.

**Comment by mreinstein** [comment]
@masx200  having looked at your last merged PR again, I've applied some fixes. 
Namely that `util.Promisify` isn't available in node 7, and also updating the unit tests to not fail with your new fixes in place. 

I've read through rfc7233, and I'm going to attempt re-writing koa-range to be more compliant with the spec. There are a lot of weird edge cases having to do with handling the presence of other http headers (e.g., `If-Match`, `If-Range`, etc.)
I'd also like to modernize the stream handling since we're relying on ancient node-isms.

I'd also like to drop the old unsupported versions of node (<= v12) but I'm not sure when to do this. It would be really nice to have as many fixes in place before dropping node versions.

**Comment by mreinstein** [comment]
I'm going to close this issue since technically the project has been updated now. :) I will create a new issue for the next steps.
